name: Update Dependencies

on:
  schedule:
    - cron: '0 3 * * 1' # Toda segunda-feira às 03:00 UTC
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Atualizar dependências
        run: pnpm update --latest
      - name: Gerar commit de atualização
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): update dependencies to latest versions" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
